from airflow.sdk import Asset

from comet.constants import (
    DATACITE_AFFILIATIONS_ENRICHMENT,
    DATACITE_FUNDERS_ENRICHMENT,
    DATACITE_RESOURCE_TYPE_GENERAL_ENRICHMENT,
    DATACITE_SOURCE,
    ROR_SOURCE,
)

ROR_RELEASE_ASSET = Asset(ROR_SOURCE.identifier)
DATACITE_RELEASE_ASSET = Asset(DATACITE_SOURCE.identifier)
DATACITE_RESOURCE_TYPE_GENERAL_ASSET = Asset(DATACITE_RESOURCE_TYPE_GENERAL_ENRICHMENT.identifier)
DATACITE_FUNDERS_ASSET = Asset(DATACITE_FUNDERS_ENRICHMENT.identifier)
DATACITE_AFFILIATIONS_ASSET = Asset(DATACITE_AFFILIATIONS_ENRICHMENT.identifier)
