from airflow.sdk import Asset

from comet.constants import (
    DATACITE_AFFILIATIONS_ENRICHMENT,
    DATACITE_DATASET_NAME,
    DATACITE_FUNDERS_ENRICHMENT,
    DATACITE_RESOURCE_TYPE_GENERAL_ENRICHMENT,
    ROR_DATASET_NAME,
)

ROR_RELEASE_ASSET = Asset(ROR_DATASET_NAME)
DATACITE_RELEASE_ASSET = Asset(DATACITE_DATASET_NAME)
DATACITE_RESOURCE_TYPE_GENERAL_ASSET = Asset(DATACITE_RESOURCE_TYPE_GENERAL_ENRICHMENT.identifier)
DATACITE_FUNDERS_ASSET = Asset(DATACITE_FUNDERS_ENRICHMENT.identifier)
DATACITE_AFFILIATIONS_ASSET = Asset(DATACITE_AFFILIATIONS_ENRICHMENT.identifier)
