{% if var.stack_tags.Environment != var.env %}
{{ environment_tag_must_match_env }}
{% endif %}
{% if var.alert_emails is not defined or not var.alert_emails %}
{{ alert_emails_must_contain_at_least_one_address }}
{% endif %}
template_bucket_name: "{{ var.template_bucket }}"

vars:
  env: dev

sceptre_user_data:
  ssm_path: "{{ var.ssm_prefix }}/dev"
  # allows stack_tags to be used in Jinja templates
  stack_tags: {{ var.stack_tags | tojson }}
  alert_emails: {{ var.alert_emails | tojson }}
  vpc_id: !stack_output_external {{ var.vpc_stack_output }}
  public_subnet: !stack_output_external {{ var.public_subnet_a_stack_output }}

  ecr:
    name: comet-dev
    tag: latest
