AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security groups used throughout the project'

Parameters:
  VpcId:
    Type: 'String'
    Description: 'The VPC ID for these security groups.'

Resources:
  CometSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub '${AWS::StackName}-SecGroup'
      GroupDescription: !Sub 'Security group deployed from ${AWS::StackName}'
      VpcId: !Ref VpcId

  CometIngressRule:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      Description: Allow inbound traffic within security group
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !Ref CometSecurityGroup
      GroupId: !Ref CometSecurityGroup

  CometEgressRule:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      Description: Allow all outbound traffic
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      CidrIp: 0.0.0.0/0
      GroupId: !Ref CometSecurityGroup

Outputs:
  CometSecurityGroupId:
    Description: The ID of the Security Group
    Value: !Ref CometSecurityGroup
