template:
  path: 'ec2.yaml'
  type: 'file'

parameters:
  ImageId: !ssm '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
  SubnetId: !stack_attr sceptre_user_data.public_subnet
  S3BucketID: !stack_output dev/s3.yaml::S3BucketID
  CometSecurityGroupId: !stack_output dev/security-groups.yaml::CometSecurityGroupId
  InstanceType: 'c5ad.16xlarge'